version: '3'

services:
    api:
        build:
            context: .
        env_file: .env
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        command: node index.js
        ports:
            - 127.0.0.1:4888:4888

